"""WindowsAppPacker — GUI-упаковщик Python-скриптов в standalone Windows EXE.

Графическая обёртка над PyInstaller: выбираешь скрипт, иконку и настройки,
жмёшь кнопку и видишь лог сборки прямо в окне.

Запуск: python WindowsAppPacker.py
Зависимости: pip install customtkinter pyinstaller
Опционально (drag-and-drop): pip install tkinterdnd2
"""
from __future__ import annotations

import os
import queue
import re
import shlex
import subprocess
import sys
import tempfile
import threading
from dataclasses import dataclass
from tkinter import filedialog, messagebox
from typing import Callable, List, Optional, Tuple

import customtkinter as ctk

try:
    from tkinterdnd2 import DND_FILES

    DND_AVAILABLE = True
except ImportError:  # optional dependency
    DND_FILES = None
    DND_AVAILABLE = False

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("green")

PY_FILETYPES = [("Python files", "*.py"), ("All files", "*.*")]
ICO_FILETYPES = [("Icon files", "*.ico"), ("All files", "*.*")]

DATA_SEP = ";" if os.name == "nt" else ":"

OutputCallback = Callable[[str], None]
DoneCallback = Callable[[int], None]

# --------------------------------------------------------------------------
# color palette (dark background + mint-green accent)
# --------------------------------------------------------------------------

COLOR_BG = "#131316"
COLOR_CARD = "#1b1c22"
COLOR_INPUT = "#212228"
COLOR_BORDER = "#2a2b33"
COLOR_TEXT = "#e6e6ea"
COLOR_TEXT_MUTED = "#8b8d98"
COLOR_ACCENT = "#1fdb7d"
COLOR_ACCENT_HOVER = "#18b967"
COLOR_DANGER = "#e5484d"
COLOR_DANGER_HOVER = "#c93d41"

ENTRY_STYLE = dict(fg_color=COLOR_INPUT, border_color=COLOR_BORDER, text_color=COLOR_TEXT)


# --------------------------------------------------------------------------
# core: build configuration model
# --------------------------------------------------------------------------


@dataclass
class BuildConfig:
    script_path: str = ""
    output_name: str = ""
    icon_path: str = ""
    output_dir: str = "dist"

    onefile: bool = True
    hide_console: bool = True
    admin_rights: bool = False

    version: str = "1.0.0.0"
    description: str = ""
    author: str = ""
    product_name: str = ""

    def validate(self) -> List[str]:
        errors = []
        if not self.script_path:
            errors.append("Не выбран исходный .py файл")
        elif not self.script_path.lower().endswith(".py"):
            errors.append("Исходный файл должен иметь расширение .py")

        if self.icon_path and not self.icon_path.lower().endswith(".ico"):
            errors.append("Иконка должна быть файлом .ico")
        return errors


# --------------------------------------------------------------------------
# core: exe version-resource generation
# --------------------------------------------------------------------------

_VERSION_TEMPLATE = """# UTF-8
#
# Auto-generated by WindowsAppPacker - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{author}'),
        StringStruct(u'FileDescription', u'{description}'),
        StringStruct(u'FileVersion', u'{version_str}'),
        StringStruct(u'InternalName', u'{product_name}'),
        StringStruct(u'LegalCopyright', u'{author}'),
        StringStruct(u'OriginalFilename', u'{output_name}'),
        StringStruct(u'ProductName', u'{product_name}'),
        StringStruct(u'ProductVersion', u'{version_str}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def parse_version(version_str: str) -> Tuple[int, int, int, int]:
    """Parses "1.2.3" / "1.2.3.4" style strings into a 4-int tuple."""
    parts = re.findall(r"\d+", version_str or "")
    numbers = [int(p) for p in parts[:4]]
    numbers += [0] * (4 - len(numbers))
    return tuple(numbers)  # type: ignore[return-value]


def build_version_file_content(
    version: str,
    description: str,
    author: str,
    product_name: str,
    output_name: str,
) -> str:
    version_tuple = parse_version(version)
    return _VERSION_TEMPLATE.format(
        version_tuple=version_tuple,
        version_str=version or "1.0.0.0",
        description=description or "",
        author=author or "",
        product_name=product_name or output_name or "",
        output_name=output_name or "",
    )


def write_version_file(path: str, **kwargs) -> str:
    content = build_version_file_content(**kwargs)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return path


# --------------------------------------------------------------------------
# core: PyInstaller command construction and build job
# --------------------------------------------------------------------------


def build_command(cfg: BuildConfig, version_file: Optional[str]) -> List[str]:
    cmd = [sys.executable, "-m", "PyInstaller", cfg.script_path, "--noconfirm"]

    cmd.append("--onefile" if cfg.onefile else "--onedir")
    cmd.append("--noconsole" if cfg.hide_console else "--console")

    if cfg.output_name:
        cmd += ["--name", cfg.output_name]
    if cfg.icon_path:
        cmd += ["--icon", cfg.icon_path]
    if cfg.admin_rights:
        cmd.append("--uac-admin")
    if cfg.output_dir:
        cmd += ["--distpath", cfg.output_dir]
    if version_file:
        cmd += ["--version-file", version_file]

    return cmd


class BuildJob:
    """Runs a PyInstaller build in a background thread and streams output."""

    def __init__(self, cfg: BuildConfig, on_output: OutputCallback, on_done: DoneCallback):
        self.cfg = cfg
        self.on_output = on_output
        self.on_done = on_done
        self._process: Optional[subprocess.Popen] = None
        self._thread: Optional[threading.Thread] = None
        self._version_file_path: Optional[str] = None
        self._cancelled = False

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def cancel(self) -> None:
        self._cancelled = True
        if self._process is not None and self._process.poll() is None:
            self._process.terminate()

    def _run(self) -> None:
        version_file = None
        try:
            if any([self.cfg.description, self.cfg.author, self.cfg.product_name, self.cfg.version]):
                fd, version_file = tempfile.mkstemp(suffix="_version_info.txt", text=True)
                os.close(fd)
                write_version_file(
                    version_file,
                    version=self.cfg.version,
                    description=self.cfg.description,
                    author=self.cfg.author,
                    product_name=self.cfg.product_name,
                    output_name=self.cfg.output_name,
                )
                self._version_file_path = version_file

            cmd = build_command(self.cfg, version_file)
            self.on_output("$ " + " ".join(shlex.quote(part) for part in cmd) + "\n")

            self._process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
                cwd=os.path.dirname(os.path.abspath(self.cfg.script_path)) or None,
            )

            assert self._process.stdout is not None
            for line in self._process.stdout:
                self.on_output(line)

            return_code = self._process.wait()
        except Exception as exc:  # surfaced to the log console
            self.on_output(f"[ошибка] {exc}\n")
            return_code = -1
        finally:
            if version_file and os.path.exists(version_file):
                try:
                    os.remove(version_file)
                except OSError:
                    pass

        if self._cancelled:
            self.on_output("\nСборка отменена пользователем.\n")
        self.on_done(return_code)


# --------------------------------------------------------------------------
# ui: reusable widgets
# --------------------------------------------------------------------------


class FilePathRow(ctk.CTkFrame):
    """Label + entry + Browse button, with optional drag-and-drop support."""

    def __init__(
        self,
        master,
        label: str,
        filetypes: List[Tuple[str, str]],
        on_change: Optional[Callable[[str], None]] = None,
        pick_folder: bool = False,
        **kwargs,
    ):
        super().__init__(master, fg_color="transparent", **kwargs)
        self.filetypes = filetypes
        self.on_change = on_change
        self.pick_folder = pick_folder

        self.grid_columnconfigure(1, weight=1)

        self.label = ctk.CTkLabel(self, text=label, width=110, anchor="w", text_color=COLOR_TEXT)
        self.label.grid(row=0, column=0, padx=(0, 8), sticky="w")

        self.entry = ctk.CTkEntry(
            self, placeholder_text="Перетащите файл сюда или нажмите «Обзор»", **ENTRY_STYLE
        )
        self.entry.grid(row=0, column=1, sticky="ew")
        self.entry.bind("<KeyRelease>", lambda _e: self._notify())

        self.browse_btn = ctk.CTkButton(
            self,
            text="Обзор...",
            width=90,
            command=self._browse,
            fg_color=COLOR_INPUT,
            hover_color=COLOR_BORDER,
            text_color=COLOR_TEXT,
        )
        self.browse_btn.grid(row=0, column=2, padx=(8, 0))

        if DND_AVAILABLE:
            try:
                self.entry.drop_target_register(DND_FILES)
                self.entry.dnd_bind("<<Drop>>", self._on_drop)
            except Exception:
                pass

    def _browse(self) -> None:
        if self.pick_folder:
            path = filedialog.askdirectory()
        else:
            path = filedialog.askopenfilename(filetypes=self.filetypes)
        if path:
            self.set(path)

    def _on_drop(self, event) -> None:
        raw = event.data
        path = raw.strip("{}") if raw.startswith("{") else raw.split()[0]
        self.set(path)

    def _notify(self) -> None:
        if self.on_change:
            self.on_change(self.get())

    def get(self) -> str:
        return self.entry.get().strip()

    def set(self, value: str) -> None:
        self.entry.delete(0, "end")
        self.entry.insert(0, value)
        self._notify()


class LogConsole(ctk.CTkTextbox):
    """Read-only, auto-scrolling textbox used to show build output."""

    def __init__(self, master, **kwargs):
        kwargs.setdefault("wrap", "word")
        kwargs.setdefault("font", ("Consolas", 12))
        kwargs.setdefault("fg_color", COLOR_CARD)
        kwargs.setdefault("text_color", COLOR_TEXT)
        kwargs.setdefault("border_color", COLOR_BORDER)
        kwargs.setdefault("border_width", 1)
        kwargs.setdefault("corner_radius", 16)
        super().__init__(master, **kwargs)
        self.configure(state="disabled")

    def write(self, text: str) -> None:
        self.configure(state="normal")
        self.insert("end", text)
        self.see("end")
        self.configure(state="disabled")

    def clear(self) -> None:
        self.configure(state="normal")
        self.delete("1.0", "end")
        self.configure(state="disabled")


# --------------------------------------------------------------------------
# ui: main application window
# --------------------------------------------------------------------------


class App(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.configure(fg_color=COLOR_BG)
        self.title("WindowsAppPacker — упаковщик Python в EXE")
        self.geometry("900x720")
        self.minsize(760, 600)

        self._build_job: Optional[BuildJob] = None
        self._log_queue: "queue.Queue[str]" = queue.Queue()
        self._done_queue: "queue.Queue[int]" = queue.Queue()

        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(2, weight=1)

        self._build_content()
        self._build_action_bar()
        self._build_log_console()

        self._check_pyinstaller()
        self._poll_queues()

    # ------------------------------------------------------------------ UI

    def _card(self, parent, title: str) -> ctk.CTkFrame:
        card = ctk.CTkFrame(parent, fg_color=COLOR_CARD, corner_radius=16, border_width=1, border_color=COLOR_BORDER)
        card.grid_columnconfigure(0, weight=1)
        header = ctk.CTkLabel(
            card,
            text=title,
            text_color=COLOR_TEXT_MUTED,
            font=ctk.CTkFont(size=13, weight="bold"),
            anchor="w",
        )
        header.grid(row=0, column=0, sticky="w", padx=16, pady=(14, 6))
        return card

    def _build_content(self) -> None:
        wrapper = ctk.CTkFrame(self, fg_color="transparent")
        wrapper.grid(row=0, column=0, sticky="ew", padx=12, pady=(12, 6))
        wrapper.grid_columnconfigure(0, weight=1)

        # --- "Основное" card ----------------------------------------------
        card_general = self._card(wrapper, "Основное")
        card_general.grid(row=0, column=0, sticky="ew", pady=(0, 10))

        self.script_row = FilePathRow(
            card_general, "Скрипт (.py):", PY_FILETYPES, on_change=self._on_script_change
        )
        self.script_row.grid(row=1, column=0, sticky="ew", padx=16, pady=4)

        output_name_row = ctk.CTkFrame(card_general, fg_color="transparent")
        output_name_row.grid(row=2, column=0, sticky="ew", padx=16, pady=4)
        output_name_row.grid_columnconfigure(1, weight=1)
        ctk.CTkLabel(output_name_row, text="Имя EXE:", width=110, anchor="w", text_color=COLOR_TEXT).grid(
            row=0, column=0
        )
        self.output_name_entry = ctk.CTkEntry(
            output_name_row, placeholder_text="MyApp (без расширения)", **ENTRY_STYLE
        )
        self.output_name_entry.grid(row=0, column=1, sticky="ew")

        self.icon_row = FilePathRow(card_general, "Иконка (.ico):", ICO_FILETYPES)
        self.icon_row.grid(row=3, column=0, sticky="ew", padx=16, pady=4)

        self.output_dir_row = FilePathRow(card_general, "Папка вывода:", [], pick_folder=True)
        self.output_dir_row.set("dist")
        self.output_dir_row.grid(row=4, column=0, sticky="ew", padx=16, pady=4)

        options_row = ctk.CTkFrame(card_general, fg_color="transparent")
        options_row.grid(row=5, column=0, sticky="ew", padx=16, pady=(10, 16))

        ctk.CTkLabel(options_row, text="Тип сборки:", text_color=COLOR_TEXT).grid(row=0, column=0, padx=(0, 8))
        self.build_type_var = ctk.StringVar(value="Onefile")
        ctk.CTkSegmentedButton(
            options_row,
            values=["Onefile", "Onedir"],
            variable=self.build_type_var,
            fg_color=COLOR_INPUT,
            selected_color=COLOR_ACCENT,
            selected_hover_color=COLOR_ACCENT_HOVER,
            unselected_color=COLOR_INPUT,
            unselected_hover_color=COLOR_BORDER,
            text_color=COLOR_TEXT,
        ).grid(row=0, column=1, padx=(0, 20))

        self.hide_console_var = ctk.BooleanVar(value=True)
        ctk.CTkCheckBox(
            options_row,
            text="Скрыть окно консоли",
            variable=self.hide_console_var,
            fg_color=COLOR_ACCENT,
            hover_color=COLOR_ACCENT_HOVER,
            border_color=COLOR_BORDER,
            text_color=COLOR_TEXT,
        ).grid(row=0, column=2, padx=(0, 20))

        self.admin_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(
            options_row,
            text="Требовать права администратора",
            variable=self.admin_var,
            fg_color=COLOR_ACCENT,
            hover_color=COLOR_ACCENT_HOVER,
            border_color=COLOR_BORDER,
            text_color=COLOR_TEXT,
        ).grid(row=0, column=3)

        # --- "Метаданные" card ----------------------------------------------
        card_meta = self._card(wrapper, "Метаданные")
        card_meta.grid(row=1, column=0, sticky="ew")
        card_meta.grid_columnconfigure(1, weight=1)

        ctk.CTkLabel(
            card_meta,
            text="Эти данные отображаются во вкладке «Подробности» свойств EXE в Windows.",
            wraplength=600,
            justify="left",
            text_color=COLOR_TEXT_MUTED,
        ).grid(row=1, column=0, columnspan=2, sticky="w", padx=16, pady=(0, 10))

        self.version_entry = self._meta_field(card_meta, 2, "Версия:", "1.0.0.0")
        self.product_name_entry = self._meta_field(card_meta, 3, "Имя продукта:", "")
        self.author_entry = self._meta_field(card_meta, 4, "Автор/компания:", "")
        self.description_entry = self._meta_field(card_meta, 5, "Описание:", "", pady_bottom=16)

    def _meta_field(self, parent, row: int, label: str, placeholder: str, pady_bottom: int = 4) -> ctk.CTkEntry:
        ctk.CTkLabel(parent, text=label, width=130, anchor="w", text_color=COLOR_TEXT).grid(
            row=row, column=0, sticky="w", padx=16, pady=(4, pady_bottom)
        )
        entry = ctk.CTkEntry(parent, placeholder_text=placeholder, **ENTRY_STYLE)
        entry.grid(row=row, column=1, sticky="ew", padx=(0, 16), pady=(4, pady_bottom))
        return entry

    def _build_action_bar(self) -> None:
        action_bar = ctk.CTkFrame(self, fg_color="transparent")
        action_bar.grid(row=1, column=0, sticky="ew", padx=12, pady=(0, 6))
        action_bar.grid_columnconfigure(2, weight=1)

        self.build_btn = ctk.CTkButton(
            action_bar,
            text="Собрать EXE",
            command=self._start_build,
            height=36,
            width=140,
            fg_color=COLOR_ACCENT,
            hover_color=COLOR_ACCENT_HOVER,
            text_color="#0b1210",
        )
        self.build_btn.grid(row=0, column=0)

        self.cancel_btn = ctk.CTkButton(
            action_bar,
            text="Отмена",
            command=self._cancel_build,
            height=36,
            width=100,
            state="disabled",
            fg_color=COLOR_DANGER,
            hover_color=COLOR_DANGER_HOVER,
        )
        self.cancel_btn.grid(row=0, column=1, padx=(8, 0))

        self.progress_bar = ctk.CTkProgressBar(
            action_bar, mode="indeterminate", fg_color=COLOR_INPUT, progress_color=COLOR_ACCENT
        )
        self.progress_bar.grid(row=0, column=2, sticky="ew", padx=16)

        self.status_label = ctk.CTkLabel(action_bar, text="Готово к сборке", anchor="e", text_color=COLOR_TEXT_MUTED)
        self.status_label.grid(row=0, column=3)

    def _build_log_console(self) -> None:
        self.log_console = LogConsole(self)
        self.log_console.grid(row=2, column=0, sticky="nsew", padx=12, pady=(0, 12))

    # ------------------------------------------------------------- helpers

    def _check_pyinstaller(self) -> None:
        try:
            import PyInstaller  # noqa: F401
        except ImportError:
            self.log_console.write(
                "[внимание] Модуль PyInstaller не найден. Установите его: pip install pyinstaller\n"
            )

    def _on_script_change(self, path: str) -> None:
        if path and not self.output_name_entry.get().strip():
            name = os.path.splitext(os.path.basename(path))[0]
            self.output_name_entry.insert(0, name)

    def _collect_config(self) -> BuildConfig:
        return BuildConfig(
            script_path=self.script_row.get(),
            output_name=self.output_name_entry.get().strip(),
            icon_path=self.icon_row.get(),
            output_dir=self.output_dir_row.get() or "dist",
            onefile=self.build_type_var.get() == "Onefile",
            hide_console=self.hide_console_var.get(),
            admin_rights=self.admin_var.get(),
            version=self.version_entry.get().strip() or "1.0.0.0",
            description=self.description_entry.get().strip(),
            author=self.author_entry.get().strip(),
            product_name=self.product_name_entry.get().strip(),
        )

    # -------------------------------------------------------------- build

    def _start_build(self) -> None:
        cfg = self._collect_config()
        errors = cfg.validate()
        if errors:
            messagebox.showerror("Проверьте настройки", "\n".join(errors))
            return

        self.log_console.clear()
        self.build_btn.configure(state="disabled")
        self.cancel_btn.configure(state="normal")
        self.status_label.configure(text="Идёт сборка...")
        self.progress_bar.start()

        self._build_job = BuildJob(
            cfg,
            on_output=lambda line: self._log_queue.put(line),
            on_done=lambda code: self._done_queue.put(code),
        )
        self._build_job.start()

    def _cancel_build(self) -> None:
        if self._build_job:
            self._build_job.cancel()
            self.status_label.configure(text="Отмена...")

    def _poll_queues(self) -> None:
        try:
            while True:
                line = self._log_queue.get_nowait()
                self.log_console.write(line)
        except queue.Empty:
            pass

        try:
            code = self._done_queue.get_nowait()
        except queue.Empty:
            code = None

        if code is not None:
            self.progress_bar.stop()
            self.progress_bar.set(0)
            self.build_btn.configure(state="normal")
            self.cancel_btn.configure(state="disabled")
            if code == 0:
                self.status_label.configure(text="Сборка успешно завершена")
            else:
                self.status_label.configure(text=f"Сборка завершилась с ошибкой (код {code})")
            self._build_job = None

        self.after(150, self._poll_queues)


def main() -> None:
    app = App()
    app.mainloop()


if __name__ == "__main__":
    main()
