"""Generates a PyInstaller ``--version-file`` resource from build metadata.

The generated file follows the format PyInstaller/pywin32 expect: a Python
module defining a ``VSVersionInfo`` structure, which PyInstaller embeds into
the resulting EXE so Windows Explorer shows the author, description and
version in the file's Properties dialog instead of blank defaults.
"""
from __future__ import annotations

import re
from typing import Tuple

_VERSION_TEMPLATE = """# UTF-8
#
# Auto-generated by WindowsAppPacker - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
    ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{author}'),
        StringStruct(u'FileDescription', u'{description}'),
        StringStruct(u'FileVersion', u'{version_str}'),
        StringStruct(u'InternalName', u'{product_name}'),
        StringStruct(u'LegalCopyright', u'{author}'),
        StringStruct(u'OriginalFilename', u'{output_name}'),
        StringStruct(u'ProductName', u'{product_name}'),
        StringStruct(u'ProductVersion', u'{version_str}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def parse_version(version_str: str) -> Tuple[int, int, int, int]:
    """Parses "1.2.3" / "1.2.3.4" style strings into a 4-int tuple."""
    parts = re.findall(r"\d+", version_str or "")
    numbers = [int(p) for p in parts[:4]]
    numbers += [0] * (4 - len(numbers))
    return tuple(numbers)  # type: ignore[return-value]


def build_version_file_content(
    version: str,
    description: str,
    author: str,
    product_name: str,
    output_name: str,
) -> str:
    version_tuple = parse_version(version)
    return _VERSION_TEMPLATE.format(
        version_tuple=version_tuple,
        version_str=version or "1.0.0.0",
        description=description or "",
        author=author or "",
        product_name=product_name or output_name or "",
        output_name=output_name or "",
    )


def write_version_file(path: str, **kwargs) -> str:
    content = build_version_file_content(**kwargs)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return path
